[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[dependencies]
rustix = { version = "0.38.37", default-features = false, features = ["system", "time"] }
rustler = "0.34.0"

[lib]
crate-type = ["cdylib"]
